class_path: data_modules.har.HarDataModule
init_args: 
  root_data_dir: data/example
  feature_column_prefixes:
    - "accel-x"
    - "accel-y"
    - "accel-z"
    - "gyro-x"
    - "gyro-y"
    - "gyro-z"
  target_column: "standard activity code"
  flatten: true
  batch_size: 64